import 'package:json_annotation/json_annotation.dart';
part 'todo.g.dart';
// This file will be generated by build_runner

@JsonSerializable()
class Todo {
  final int userId;
  final int id;
  final String title;
  final bool completed;

  Todo({
    required this.userId,
    required this.id,
    required this.title,
    required this.completed,
  });

  //Factory methods to convert JSON to Todo object and vice versa
  factory Todo.fromJson(Map<String, dynamic> json) => _$TodoFromJson(json);

  Map<String, dynamic> toJson() => _$TodoToJson(this);
}